// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5bC5wARwE6qiAWqVlvN1CiZ8O9EQ0cG8',
    appId: '1:791254720557:web:e5413ff5e01101e36058a4',
    messagingSenderId: '791254720557',
    projectId: 'spotify-bd7d7',
    authDomain: 'spotify-bd7d7.firebaseapp.com',
    storageBucket: 'spotify-bd7d7.appspot.com',
    measurementId: 'G-78WSMZDVQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAjUfg39jCdKRr3eTeymuy_emPWbBbWo',
    appId: '1:791254720557:android:133bc19203330af66058a4',
    messagingSenderId: '791254720557',
    projectId: 'spotify-bd7d7',
    storageBucket: 'spotify-bd7d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjnMFtOFZdISmC50LHWGJo2znpencT6I',
    appId: '1:791254720557:ios:b6ab0af1861a2b286058a4',
    messagingSenderId: '791254720557',
    projectId: 'spotify-bd7d7',
    storageBucket: 'spotify-bd7d7.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjnMFtOFZdISmC50LHWGJo2znpencT6I',
    appId: '1:791254720557:ios:b6ab0af1861a2b286058a4',
    messagingSenderId: '791254720557',
    projectId: 'spotify-bd7d7',
    storageBucket: 'spotify-bd7d7.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5bC5wARwE6qiAWqVlvN1CiZ8O9EQ0cG8',
    appId: '1:791254720557:web:ed958e39312e23226058a4',
    messagingSenderId: '791254720557',
    projectId: 'spotify-bd7d7',
    authDomain: 'spotify-bd7d7.firebaseapp.com',
    storageBucket: 'spotify-bd7d7.appspot.com',
    measurementId: 'G-KQXZ5J69Q1',
  );
}